#! /bin/bash

REF="$(git branch --show-current)"

if [ -n "${REF}" ]; then
    SOURCE_BRANCH="$(basename "${REF}")"
    TEST_BRANCH="test/${SOURCE_BRANCH}"

    git switch "${TEST_BRANCH}" || git switch -c "${TEST_BRANCH}"
    git fetch "${SOURCE_BRANCH}"
    git merge "${SOURCE_BRANCH}"
    git push --no-verify

    git switch "${SOURCE_BRANCH}"
fi
