#pragma once

#include "action/base.hpp"
#include "action/null.hpp"
#include "action/range_add.hpp"
#include "action/range_add_range_max.hpp"
#include "action/range_add_range_min.hpp"
#include "action/range_add_range_sum.hpp"
#include "action/range_affine_range_minmax.hpp"
#include "action/range_affine_range_sum.hpp"
#include "action/range_bitxor.hpp"
#include "action/range_gcd.hpp"
#include "action/range_max.hpp"
#include "action/range_min.hpp"
#include "action/range_set_range_max.hpp"
#include "action/range_set_range_min.hpp"
#include "action/range_set_range_sum.hpp"
#include "action/range_sum.hpp"
