#pragma once

#include "algebraic/addition.hpp"
#include "algebraic/affine.hpp"
#include "algebraic/assignment.hpp"
#include "algebraic/base.hpp"
#include "algebraic/bit_and.hpp"
#include "algebraic/bit_or.hpp"
#include "algebraic/bit_xor.hpp"
#include "algebraic/combined.hpp"
#include "algebraic/gcd.hpp"
#include "algebraic/helper.hpp"
#include "algebraic/maximum.hpp"
#include "algebraic/minimum.hpp"
#include "algebraic/minmax.hpp"
#include "algebraic/null.hpp"
#include "algebraic/opposite.hpp"
#include "algebraic/rolling_hash.hpp"
